openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /greet:
    get:
      summary: Get a friendly greeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Hello, world!
