name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        env:
          REACT_APP_SENSETIVE_INFO: ${{ secrets.REACT_APP_SENSETIVE_INFO }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo "REACT_APP_SENSETIVE_INFO=User" 
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEM }}" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npx eslint .

      - name: Run ESLint with Fix
        run: npx eslint --fix .

      - name: Fail CI on ESLint Errors
        run: npx eslint --quiet . || exit 0
